### ISSUE TITLE
Radar Export to secondary screen

### ISSUE THREAD

**Issue by NeroDCS** [heclak/community-a4e-c#129]
seems so far this isnt implemented.

**Comment by WarLord211** [comment]
https://forums.eagle.ru/showpost.php?p=3888812&postcount=1393

**Comment by heclak** [comment]
@WarLord211 thanks for linking the post. We already have the base export worked out but I'll try and see if we can take it further with exporting the scale as well. Will be using a custom name instead of the LEFT/RIGHT_MFCD so people can customise their setups better. Will definitely include at least the base export in the next release and update the manual as well.

**Comment by heclak** [comment]
Added in v1.4
