### ISSUE TITLE
Aileron trim does not work when used with MS FFB2

### ISSUE THREAD

**Issue by Voltigo** [heclak/community-a4e-c#137]
The aileron trim doesn't apply. I can't trim at all the ailerons. And I think it makes my AFCS no function.

Can you tell me if you can find a solution or if my problem if between the chair and the keyboard?

 - DCS Version: DCS 2.5.4.30386 (Stable)
 - A-4E Version  v1.3

PS : I love my scooter, thank you

**Comment by heclak** [comment]
Can you provide the steps you took to recreate this bug? Are you using a joystick or keyboard? I've just tested the aileron trim and it works fine for me. Have you checked if your joystick or keybindings are correctly mapped? 

What problems are you having with the AFCS? Is the engage switch not staying in the engaged position or are you not able to turn on Alt Hold or Heading Sel? 

We need more details to help figure out if it is a bug. Thank you.

**Comment by Voltigo** [comment]
I use a very old MS Sidewinder Force Feedback pro 2. I use the trim hat at the top of the joystick. The pitch trim works but not the roll trim. I tried using the keyboard. The trim hat on the screen seems to move, but not the trim needle. And the plane keeps its behaviour.

The same thing happen for the AFCS. I flip the switch, but nothing happens. But the switchs stay at position. 

Do I use badly? I don't know.

**Comment by heclak** [comment]
Have you tried rebinding the joystick/keyboard to make sure it’s not a binding issue? The trim response definitely changes but I didn’t check the needles. I’ll check if they are correct later. 

The AFCS switch are magnetic and will auto reset in certain conditions. It is best if you give an example of which AFCS mode are you trying to engage and what steps were taken. 

Did you upgrade from an earlier version? If you did then you can try deleting the A-4E and downloading a fresh copy for a fresh install. That helps if you have any corrupted files.

**Comment by Voltigo** [comment]
Hi!
I've tried that, and I've formatted my hard drive a few weeks ago. The problem is here since 1.1.

My steps: I start the mission with a hot start (the aircraft is already lined up). Take of. the main switch is already on stand by: I pitch trim my sky' click the engage switch and the altitude trim.

The 1.3 version had so many changes I rebinded all my controls from scratch. And I refreshed my files. 

Do you think I have to refresh again?

By the way, nice job. I love this baby. And if you want to have funny paints, I'd love to have de Buck Danny's one! :)

**Comment by heclak** [comment]
Which switches jump back into the off position? When you say altitude trim, are you referring to the altitude hold switch?

Altitude hold will not engage when vertical speed is greater than 4000 feet per minute. You also need to make sure there is no movement in the stick. Have you tried it without the joystick? Maybe there is some jitter in the joystick that is causing it to disengage the AFCS?

When you delete reinstall the A-4E-C, did you delete old Input folder? It's in SavedGames/DCS/Config/Input/A-4E-C

**Comment by Voltigo** [comment]
No switch jump back to off. It looks like the AFCS is JUST disconnected. 
What's the right process to activate it?
Do you know if roll trim needle moves? Because the trim hat on the stick (in the plane) moves, but nothing else.

I didn't try with the joystick disconnected. But I won't play without joystick so, if the problem is the stick, I will fly without AFCS. For info, other modules work with this joyctick. And their AFCS too.

I replaced the input folder. Nothing changes. 

That is NOT a big problem but if my skyhawk can be a little more comfortable.....

Other question : do you plan to make the LABS active? And the Walleye?

Thank you for your help.

**Comment by heclak** [comment]
The AFCS is too complicated to explain here. There's some explanation of it in the guide (https://docs.google.com/presentation/d/1cUH7jpAoGHm-IzUDnv_NDhiZlvX55Q9WvpgR1d9ksYY/edit#slide=id.g45fb1305f8_91_24) but it is best to download a copy of the NATOPS to read through it in detail. 

There is no roll/aileron trim gauge in the A-4E. What gauge are you looking at? There is only a pitch trim indicator on the top of the right console.

Yea. We can't compare with other modules because there are different systems logic in different aircraft. The A-4E AFCS is not the same as other aircraft autopilot and is actually one of the harder ones to use as it is one of the oldest. There are no displays or warning lights if you use it wrongly. Most aircraft do not have an AFCS logic that is as difficult to learn as the A-4E.

[A-4E Caucausus Takeoff Nav.zip](https://github.com/heclak/community-a4e-c/files/3289658/A-4E.Caucausus.Takeoff.Nav.zip)

Try it with this mission.
1. Takeoff and fly straight. 
2. Climb above 1000ft and trim to level flight. Let go of the stick.
3. Make sure AFCS standby switch is still on. Toggle AFCS Engage switch to the ENGAGE position
4. Toggle AFCS ALT switch to ALT position.

The aircraft will take some time to level out and then maintain the altitude the aircraft was at the moment the ALT switch was switched to the ALT position.

Let me know how that works out for you.

**Comment by Voltigo** [comment]
I tried the mission.
The problem is : I cannot aileron trim the plan. When I pitch trim, my skyhawk starts to roll left hand.

I think the bad trimming doesn't permit the AFCS to engage. 

But Why my f.....ing aileron trim doesn't want to operate? It's up to date, installed in a stylish plane, operated by a wonderful pilot. Why is it so lazy?

Thank you Heclak for your efforts, and for this wonderful module.

**Comment by RevMagnum** [comment]
Hey guys first of all I'm recently back to DCS with my new pc (I had to leave during 1.2) . I'm absolutely stunned and overwhelmed with the community A4. It is an excellent job and I'm personally **grateful** for all the hard work and time you put in it. Among its many qualities my favorite and the most promising is the "community" part :) **Thank you** on behalf of many Skyhawk fans like me...

I'm also an old MS FF2 user and have been experiencing the erratic trim since dcs1.2 or so (trimming up used to roll the plane etc.). One solution recently read was to swap FF axis and it **fixed** it...However on A4E-C 1.3.1 I experience the exact same problems like Voltigo with my roll trim and AFCS engagement. I suspect MSFF2 is the culprit. First I'm gonna put a deadzone then will disconnect the jstick entirely to test it. I worry if DCS would wipe the bindings if I start it without the j/s plugged in.

**Comment by heclak** [comment]
Ok. So I finally had the time to take out my FFB2 to test it out. And I can confirm there are issues with the aileron trim and AFCS when the MS FFB2 is used. These problems are specific to the FFB2 and DCS. The roll trim is probably due to a DCS detecting an FFB stick and changing how the trim controls work. If you connect the FFB2 after the mission has started then the aileron trim works. But if you go into the "Adjust Controls" menu then the aileron trim will stop working again. The sim has probably reloaded the FFB code then. This will require some time to figure out how to resolve this, it probably requires rewriting how the trim functions work as FFB sticks have a feedback loop.

As for the AFCS, I believe it is also related to how FFB works. It is definitely related to the FFB implementation as the AFCS has to take over the control surfaces. So when the AFCS moves the controls, the stick will move and cause the AFCS to disengage. Putting a dead zone doesn't help with the AFCS. This might require a rewrite of the AFCS just to work with the AFCS so I'm not sure if I'll around to this anytime soon if at all. 

I'll try and see if the issue with aileron trim can be solved first as that is more important than the AFCS. But no guarantees that it will be possible as the FFB functions are only available in the EFM function calls.

**Comment by heclak** [comment]
Good news. I think I've solved the aileron trim issue. I'll need some FFB2 owners to confirm. I've attached a zip file that contains a file named trim.lua. Replace the file in A-4E-C/Cockpit/Scripts/Systems/trim.lua with this file and aileron trim should work. AFCS will not work. I'll need to refine the trim code further before integrating the code changes with the main code

[trim.zip](https://github.com/heclak/community-a4e-c/files/3355143/trim.zip)

**Comment by Voltigo** [comment]
Holy you!
Thank you for your effort and for not just say me "buy a fucking joystick, you bitch".
I will try it. And send an issue to eagle Dynamics for that. 

"Oooooh, I've seen on some planes: The tomcat, the Sukhoi, the mig and the ... And The-one-which-cannot-be-named!!!!!"

**Comment by RevMagnum** [comment]
I couldn't come around to test it before but just now I read what heclak wrote and did some quick tests and can totally confirm the same results; AFCS n aileron trim works like a charm without the FFB2 plugged in. I don't know if it helps but with FFB2 plugged, putting %100 deadzone, 0 saturation, 0 FF etc. thus rendering j/s inert, also disables whole a/c controls (even if keyboard roll or trim up commands work, stick won't move) It may be related to how DCS handles the whole control input/output array. 

Thank you for the trim.lua and it does the trick for the aileron trim as you've said. I'm so bummed about the AFCS after I've seen how gently and realistic it can work without my double-decade old j/s (heard it from a Skyhawk guy that the real thing wasn't a wonder but did the job). I don't mind much about the aileron trim but I like to do long flights preferably with an alt n level hold. Well I can still enjoy this beautiful bird without x32 simrate cruise flights. 

This finding of FFB2 mishap can shed light to many others suffering from related issues. 

Heclak, once again, thank you for your work and time:)


I

**Comment by Voltigo** [comment]
Hi (sorry to be late, my CPL and my newborn son take all my free time).
Unfortunately my trim doesn't seem to work better.
I have emitted a ticket to eagle Dynamics. We will see how they will handle it.

Thank you for your support.

**Comment by Voltigo** [comment]
Hi!

ED answered me for the FFB2 troubleshoot.

Alexander Bilievskiy08/06/2019 14:13:54Quote
 Swap Axis.JPG (170.38 Kb)
Hello,
For FFB2 you need to enable Swap Axis option in the FFB settings.
