### ISSUE TITLE
allow sidewinder AA missiles on outboard stations in loadouts

### ISSUE THREAD

**Issue by uriba107** [heclak/community-a4e-c#224]
**Describe the bug**
Air to air missiles on A-4s are carried on outboard pylons. And not inboard as it is here currenly.

Only A-4B and A-4C carried missiles in the inboard stations as they only had one station per wing.

I'm working on a fix in a fork to be merged (along with some more tweaks to livery and payloads according to IDF/AF photos and driver reports like 4*M177 on centerline pylon).

Just wanted to clear this with you guys before pushing changes

**Additional context**
![399-1ms_filtered](https://user-images.githubusercontent.com/6206564/83328254-5694cb80-a28a-11ea-80ad-504e389e0930.jpg)
![15885_wa](https://user-images.githubusercontent.com/6206564/83328256-57c5f880-a28a-11ea-82c5-3627970f7ac5.jpg)

Note the tailpipe extension, indicative of A-4H, A-4N or an A-4E/F upgraded to H standard (which included installation of the hump).

**Comment by heclak** [comment]
Hi uriba107,
referencing the NATOPS for the E/F model, the sidewinders are only mounted on stations 2 and 4 which are the inboard station. This is due to the set up of the wiring harness needed for the sidewinders which were only added to stations 2 and 4. The export models which were renamed eg. K, H, N, etc had the wiring harness add on their own. 

Since we are only referencing the E model, we decided to keep the sidewinders set up accurate to the E models. Expanding the naming of the aircraft to include the other models would result in having to include everything of the other models as well and the systems are wildly different between the models. However, if you can find information about an E model (not upgraded to another countries' model) having the missiles on the outboard pylons then we can look into that.

**Comment by uriba107** [comment]
Thanks.
does the G count as it is the export variant for of the E/F? :)

I can't find any stores limitations in NATOPS other then weight limitations.

**Comment by Bungo71** [comment]
The G was a development/modification of the F without the hump.  I have seen photos of them with sidewinder on the 2 wing pylons, but have never seen photos of them with 3 wing stations.  I think as thie A4G was primarilly a fleet defence fighter, that sidewinder ability was a local specification. 

from:  [Fleet Air Arm - Skyhawk: History in Photographs](https://www.faaaa.asn.au/skyhawk-history-photographs/)
"The RAN ordered ten brand new A4s, originally to be built as “E” model variants, early in 1964 (see letter below).  The finished “G” model lacked the avionics of the USN A4-F, but was fitted to carry up to four Sidewinder missiles.  Eight of the ten were single seat fighter-bombers and the remaining two the TA4G training variant, with two seats.  The total project cost was reported as $18.4m – relatively cheap for an aircraft of that capability."

**Comment by uriba107** [comment]
I'm adding a link to YT.
it's part of and interview with two veteren A-4 Pilots from USN. the link is timespamped to a part where "Demon" the second pilot interviewed expands a little on his experience with the Intrepid operating A-4E (Super-E as he called it, with the hump) with VA-45. he specifically mentioned their carrying two Sidewinders on the outboard wing stations (further detailing they were the 1/5 stations)
it's about a 5 minutes piece of audio (00:58:55 - 1:04:00 ) config is mentioned in 1:01:20 

https://youtu.be/2eah13pmp9Y?t=3535

Cheers :)

**Comment by callmepartario** [comment]
this is slated to be addressed in the next beta
