### ISSUE TITLE
lights automatically turn on at night when spawned 

### ISSUE THREAD

**Issue by Kerbo416** [heclak/community-a4e-c#247]
hello, it's kerbo, you asked me to add it as an issue

**Comment by callmepartario** [comment]
not sure how to interpret this, kerbo, do the lights turn on at night by default and that's incorrect, or do they *not* turn on and you wish they would? mission files often include flags to set cockpit switches to the desired position upon mission start.

either way, since this is a combat aircraft, i don't think i'd want them to default to on. i am not sure how easy it would be to define a cockpit's in-air defaults as dictated by the time of the mission start, or if that's really a good return on investment since any desired state is possible in the mission editor.

**Comment by 08jne01** [comment]
Note sure what this defect is really about but I've changed the lights to be on between 1700 and 0500.
