### ISSUE TITLE
Ground handling Turn radius and brakes...

### ISSUE THREAD

**Issue by Baco1170** [heclak/community-a4e-c#281]
**Describe the bug**
1- Turn radius too wide. 
Imposible to maneuver on deck.
2- Brake have very little stopping power

**To Reproduce**
try to turn on ground or carrier.

**Expected behavior**
the turn radius should be much, much smaller.
Brakes should be more efective And while turning with deferential brakes it shuold make the turn radius smaller yet.

Ver. latest FM Beta (2.0)

**Comment by 08jne01** [comment]
Hello this is two separate defect reports.

The turning radius is accurate as described in the manual it can turn about one of it's main gear, you are likely not coming to a full stop before applying the differential brakes.

The braking force is very poor in the real scooter, please make use of the spoilers when landing.

**Comment by Baco1170** [comment]
The Plane does not turn constantly but slips, and has no traction, it it imposible to manoeuvre on the deck. Please revise.  
Keep in mind we dont have pushback, or fligth directors. For Carrier operations it would be nice to have an extra tool to position ourselves on Deck.

Thanks!!!

**Comment by 08jne01** [comment]
> The Plane does not turn constantly but slips, and has no traction, it it imposible to manoeuvre on the deck. Please revise.
> Keep in mind we dont have pushback, or fligth directors. For Carrier operations it would be nice to have an extra tool to position ourselves on Deck.
> 
> Thanks!!!

Hello, just come to a full stop, hold one brake with the **nose wheel steering disengaged** and then increase power until the plane pivots about the wheel with the brake held.

It is important you do not engage the nosewheel steering during this because it limits the nosewheel to 45 degrees as per the NATOPS. With the nosewheel steering disengaged the nosewheel is free castoring as such it can be more easily turned using the wheelbrakes.
