### ISSUE TITLE
keybinds for wheel brakes are non-functional

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#345]
**Describe the bug**
input config defaults are calling for Keys.BrakesOn, Keys.BrakesOnLeft and Keys.BrakesOnRight, but these three bindings are not pressing the brakes. axis inputs for all wheel brakes seem unaffected. Wasn't sure where to look, these are likely EFM specific binds.

**Software Information (please complete the following information):**
 - DCS 2.7 Open Beta
 - A-4E v2.0.0-beta 4 (dev)

**Comment by 08jne01** [comment]
This was fixed in: c2360aeb5f386d0b9d35678c38cc500724658c86

Worth putting this here just in case anyone reads it: 

`EFM commands have been moved to the start of the Keys table definition.

This is so that commands can be added after this without changing the
value of these.

These must be built directly into the dll because runtime values cannot
be used with switch statements. The Generate_Control_Headers.exe will
generate the Commands.h and Devices.h headers containing the key and
device commands and the device numbers.`
