### ISSUE TITLE
Additonal mouse button bindings

### ISSUE THREAD

**Issue by FluerdeLune** [heclak/community-a4e-c#442]
Ver. A-4E-C_v2.0.0-RC2

I added the "Zoom normal" and "View Center" on the mouse. 
Can be this added by default if possible pls? Thank you.

File Location: \A-4E-C\Input\mouse\default.lua
Code:
return {

keyCommands = {
{combos = {{key = 'MOUSE_BTN2'}}, down = iCommand_ExplorationStart, name = _('Enable visual recon mode'), category = _('View Cockpit')},
{combos = {{key = 'MOUSE_BTN3'}}, down = iCommandViewTransposeModeOn, up = iCommandViewTransposeModeOff, name = _('Camera transpose mode (press and hold)'), category = _('View Cockpit')},
{down = iCommandCockpitClickModeOnOff,			name = _('Clickable mouse cockpit mode On/Off'), category = _('General')},
{down = iCommandViewAngleDefault, name = _('Zoom normal'), category = _('View')},
{pressed = iCommandViewCenter, name = _('View Center'), category = _('View')},
},

axisCommands = {
-- mouse axes
{combos = {{key = 'MOUSE_X'}}, action = iCommandPlaneViewHorizontal, name = _('Camera Horizontal View')},
{combos = {{key = 'MOUSE_Y'}}, action = iCommandPlaneViewVertical, name = _('Camera Vertical View')},
{combos = {{key = 'MOUSE_Z'}}, action = iCommandPlaneZoomView, name = _('Camera Zoom View')},

},
}

**Comment by callmepartario** [comment]
while i appreciate the sentiment, i'm a little reluctant to do extended mouse button bindings. i know people who use them for various push to talk/radio or other functions on the regular as a matter of course, and since DCS itself has provided no guidance on the subject, i would want to see more users weighting in on this one for what they use their additional mouse buttons for. i'm going to table this for now, and see if we get any other input on the subject.
