### ISSUE TITLE
APC status light remains on after being engaged

### ISSUE THREAD

**Issue by robscallsign** [heclak/community-a4e-c#463]
**Describe the bug**
APC light turns on after the 15 second warmup period in standby, but remains on after being engaged.  

**To Reproduce**

**Expected behavior**
APC light should turn off when engaged according to NAVAIR 01-40AVM-1 and NAVAIR 01-40AVF-1 - A-4E&F NATOPS.

**Screenshots**
Landing at an airfield, APC engaged and working, APC light still enabled:
https://cdn.discordapp.com/attachments/411346491542601730/921578557900214323/unknown.png
https://cdn.discordapp.com/attachments/411346491542601730/921578650573344818/unknown.png

Expected behaviour:
NAVAIR 01-40AVF-1 - A-4E&F NATOPS - 1971 edition.pdf page 125:
https://cdn.discordapp.com/attachments/768471088010362893/921919688563359845/unknown.png

NAVAIR 01-40AVM-1 - A-4M NATOPS - 1971 edition.pdf page 29
![image](https://user-images.githubusercontent.com/49131756/146659091-c9c19cda-f94e-4044-a40e-01e907cb5a48.png)
https://cdn.discordapp.com/attachments/768471088010362893/921920025030434856/unknown.png

**Comment by pohlinkzei** [comment]
Hi there, I had a look into this and found that there are two afcs*.lua files. I guess afcs.lua holding the current code and afcs2.lua some old sfm code. What I observed is that both files are referenced in the code:
```
grep -r "afcs.lua" .
./A-4E-C/ExternalFM/handles.txt:  C:\Users\joshn\Saved Games\DCS.openbeta\Mods\Aircraft\A-4E-C\Cockpit\Scripts\Systems\afcs.lua (10 hits)
```
and
```
grep -r "afcs2.lua" .
Binary file ./.git/index matches
./A-4E-C/Cockpit/Scripts/device_init.lua:creators[devices.AFCS]            = {"avLuaDevice"           ,LockOn_Options.script_path.."Systems/afcs2.lua"}
```
In afcs.lua, the light switches off, when the APC is engaged, but in afcs2.lua it is still - or better set - on. I think only one of both files should be used by the code, but since I am not sure, I'd ask. :)

When I changed the bahaviour in afcs2.lua, the behaviour changed to the way it should trigger the light.

**Comment by callmepartario** [comment]
Fixed in https://github.com/heclak/community-a4e-c/pull/515 !
