### ISSUE TITLE
Cockpit switches with inverted mouse interaction behavior

### ISSUE THREAD

**Issue by peeecet** [heclak/community-a4e-c#501]
In the right console panel ALL the 3 position switches are binded in the opposite direction. 

Click on one of the 3 position switches on the right control panel (e.g. TACAN ANT, MCL PWR, FLOOD LTS, EXTR LTS.. ): with RMB the switch goes DOWN, with LMB the switch goes UP.
In the rest of the cockpit and in the official modules the default behaviour is: RMB-UP, LMB-DOWN.
Rotary switches behave normally.

Software Information 
 - DCS Version: DCS 2.7.9.18080 Open Beta
 - A-4E Version 2.0

**Comment by callmepartario** [comment]
while this is technically an inverted 3d animation arg issue, it's fixable in code. 

- i've created `inverted_3_position_tumb` and `multiposition_switch_limited_inverted` types in `clickable_defs.lua`, for the `Instrument Lights Brightness` switch, and the `TACAN Antenna Control Switch (unimplemented)`.
- i edited the `springloaded_forward_only_3_pos_tumb` type in `clickable_defs.lua` to set up the inversion. it's the only switch of this type, so i see no need to create a new entry.

fixed in https://github.com/heclak/community-a4e-c/commit/83aa7013f1daa46952ed0ad5dd71c0ea2b06ccf0
