### ISSUE TITLE
Nose steering not working with rudder input

### ISSUE THREAD

**Issue by muadib25** [heclak/community-a4e-c#523]
**Describe the bug**
The aircraft's nose wheel does not respond to rudder input.

**To Reproduce**
1. Follow normal startup procedure
2. Try to taxi using rudder input

**Expected behavior**
Nose wheel should turn according to rudder inputs

**Software Information (please complete the following information):**
 - DCS Version: 2.7.10.19473
 - A-4E Version 2.0

**Comment by callmepartario** [comment]
you need to use the brakes to turn. if you want to give nosewheel directional input with the rudder instead of the differential left/right brake keys or pedals, you will need to enable that option in the dcs special menu.

for tips on ground handling, see https://www.youtube.com/watch?v=gQOTZB8PqwA and https://www.youtube.com/watch?v=yt9iu7wKWrg
