### ISSUE TITLE
CBU-2B/A pod weight

### ISSUE THREAD

**Issue by callmepartario** [heclak/community-a4e-c#526]
seen here, with two cbu 2b/as, showing a loadout of 42,000 lbs

![image](https://user-images.githubusercontent.com/17432407/156965113-2c127300-5cab-451e-b92c-ad129c8a4585.png)

**Software Information (please complete the following information):**
 - DCS Version: [e.g. DCS 2.7.10 Open Beta]
 - A-4E Version [e.g. v2.0.1]

**Comment by nairb121** [comment]
CBU-1 and CBU-2 dispense in bursting clusters instead of streams from pods. In the case of CBU-2, the burst sends bomblets in all directions, often impacting and destroying the aircraft. Test mission and track attached, showing aircraft destruction when using CBU-2.
[A-4 CBU Test.zip](https://github.com/heclak/community-a4e-c/files/8236668/A-4.CBU.Test.zip)
