### ISSUE TITLE
Communication menu does not appear

### ISSUE THREAD

**Issue by JF5141** [heclak/community-a4e-c#545]
Communication menu does not open in any mission
What should i do?

DCS World 2.7

**Comment by callmepartario** [comment]
You probably are failing to use the associated `Radio Microphone Push to Talk (PTT)` binding. The default keybind is `RAlt+\`

As with most modules, you need to use the radio button rather than the communications menu when communicating by radio. Additional details are provided in the kneeboard manual.

If you need operational help with the module, the Discord is a much better place to get sorted than the issue tracker.

**Comment by JF5141** [comment]
I'll get it, thanks and sorry.

**Comment by callmepartario** [comment]
no problem, hope that binding gets you sorted on this issue! In the A-4E-C, the generic comms menu is only what you'll use when you're communicating with the ground crew (with your canopy open). Almost everything else will use the Radio PTT with a properly configured and powered radio.
