### ISSUE TITLE
"Throttle position - Increment/Decrement" binds do not work

### ISSUE THREAD

**Issue by DinkleDorph** [heclak/community-a4e-c#552]
These binds do nothing. Not sure if this is just a bug or an oversight.

More info can be seen here: https://www.reddit.com/r/hoggit/comments/wnqkjq/cant_throttle_up_or_down/

**Comment by callmepartario** [comment]
your throttle axis input must be ZERO for these bindings to function. open your controls indicator by pressing RCTRL+ENTER and note the position of the axis input - the red "ghost" input moving as you move your throttle means that the throttle input is being moved, but the STEP position is not allowing throttle position change.

**Comment by Tuuvas** [comment]
@callmepartario I just tested this and found "Throttle Position - Decrement" (default: Page Down) and "Throttle Position - Increment" (default: Page Up) do not work.  In my testing I made sure there is only a keyboard connected to rule out any default axis throttle binding, as well as used a hot start mission to rule out startup procedure.  See steps below:

1. Instant Action -> A-4E-C -> Caucasus -> Takeoff
2. Click green fly button
3. Look down at the throttle
4. Mash "Throttle Position - Increment" (default: Page Up) like a Ken player trying to wakeup shoryuken
- Expected Results: Throttle should increase some set % of movement with each press
- Actual Results: Throttle does not move.

Note: throttle moves with continuous just fine.  This issue seems to only affect incremental/decremental movements.

**Comment by callmepartario** [comment]
ah, okay, i see now.

looks like at some point `iCommandPlaneAUTIncreaseRegime` and `iCommandPlaneAUTDecreaseRegime` have gone the way of the dodo, while the continuous inputs, `iCommandThrottleIncrease`, iCommandThrottleDecrease`, and `iCommandThrottleStop` are all still functional. There are iCommands and so are DCS-issued. i'll see what i can dig up on this. 

these kinds of keybinds are most useful for people whose keyboards give repeat inputs instead of holds, but could also be useful for rotary inputs or things like that in alternate controller setups.

**Comment by callmepartario** [comment]
Fixed in https://github.com/heclak/community-a4e-c/commit/7998d11602d402003e1c7ca3716fad61b5acc630  - thanks for the heads up. This will also introduce a slider where you can set the rate of the increment from 1% to 5%, with 0.1% granularity. The default rate of change is set to 2.5%.

**Comment by callmepartario** [comment]
added additional else configuration options in https://github.com/heclak/community-a4e-c/commit/8b7891c0ccce8e89f647c9c9d717defd2d342a33

**Comment by callmepartario** [comment]
closing this as we move toward the next release. this is a nice fix and prompted a lot of larger related conversations about inputs!
