### ISSUE TITLE
AoA Compensation Switch

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [heclak/community-a4e-c#666]
Hi,

1. What does the AoA Compensation Switch do exactly?
2. I noticed the kneeboard manual says to have the switch ON in all radar modes except for A/G mode. Why is that?

Thanks, great job on the mod!

**Comment by callmepartario** [comment]
The angle-of-attack switch enables the pilot to remove the angle-of-attack compensation for line-of flight reference for the various modes the airflow sensor becomes inoperative. With the angle-of-attack switch in the OFF position, the zero line on the indicator is referenced to the armament datum line rather than to the flight path.

Please refer any further operational questions like this to the discord community instead of the issue tracker, this space is to deal with issues related to the software.
